# Generated by Django 3.1 on 2021-05-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210513_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='care_type',
            new_name='car_type',
        ),
    ]
