# Generated by Django 3.1 on 2021-05-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210514_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.IntegerField(choices=[('Седан', 'Седан'), ('Хэчбэк', 'Хэчбэк'), ('Унивесал', 'Универсал'), ('Купе', 'Купе')], verbose_name='Car_Type'),
        ),
    ]
