# Generated by Django 3.1 on 2021-05-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210514_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Седан', 'Седан'), ('Хэчбэк', 'Хэчбэк'), ('Унивесал', 'Универсал'), ('Купе', 'Купе')], max_length=40, verbose_name='Car_Type'),
        ),
    ]
